import 'dart:core';

import '../team/v1/team.pb.dart' show AccessRequest;
import 'lan_client.dart';

/// A short-lived invitation encoded by a Robot Command pairing QR code.
///
/// The invitation contains connection and pairing material only. It never
/// contains an observer session token or snapshot data.
final class RobotCommandPairingInvitation {
  RobotCommandPairingInvitation({
    required this.endpoint,
    required this.certificateFingerprint,
    required this.pairingId,
    required this.shortCode,
    required this.expiresAt,
    this.passphrase = '',
  });

  static const scheme = 'logos-robot-command';
  static const host = 'pair';
  static const path = '/v1';

  final Uri endpoint;
  final String certificateFingerprint;
  final String pairingId;
  final String shortCode;
  final DateTime expiresAt;
  final String passphrase;

  bool get isExpired => !expiresAt.isAfter(DateTime.now().toUtc());

  /// Parses the QR URI format generated by Robot Command.
  factory RobotCommandPairingInvitation.parse(String value) {
    final uri = Uri.tryParse(value.trim());
    if (uri == null ||
        !uri.isAbsolute ||
        uri.scheme.toLowerCase() != scheme ||
        uri.host.toLowerCase() != host ||
        uri.path != path) {
      throw const FormatException('Enter a valid Robot Command pairing link.');
    }

    final endpointText = uri.queryParameters['endpoint'];
    final endpoint = endpointText == null ? null : Uri.tryParse(endpointText);
    if (endpoint == null || endpoint.scheme.toLowerCase() != 'https') {
      throw const FormatException(
        'The pairing link does not contain a valid HTTPS endpoint.',
      );
    }

    final fingerprint = uri.queryParameters['fingerprint'];
    final pairingId = uri.queryParameters['pairing_id'];
    final shortCode = uri.queryParameters['code'];
    final expiresText = uri.queryParameters['expires'];
    final expiresSeconds =
        expiresText == null ? null : int.tryParse(expiresText);
    if (fingerprint == null ||
        pairingId == null ||
        pairingId.isEmpty ||
        shortCode == null ||
        shortCode.length != 6 ||
        !_isAsciiDigits(shortCode) ||
        expiresSeconds == null) {
      throw const FormatException('The pairing link is incomplete or invalid.');
    }

    final expiresAt = DateTime.fromMillisecondsSinceEpoch(
      expiresSeconds * 1000,
      isUtc: true,
    );
    if (!expiresAt.isAfter(DateTime.now().toUtc())) {
      throw const FormatException(
        'The pairing link has expired. Create a new QR code on the host Robot Command.',
      );
    }

    return RobotCommandPairingInvitation(
      endpoint: endpoint,
      certificateFingerprint: RobotCommandLanClient.normalizeFingerprint(
        fingerprint,
      ),
      pairingId: pairingId,
      shortCode: shortCode,
      expiresAt: expiresAt,
      passphrase: uri.queryParameters['phrase'] ?? '',
    );
  }

  /// Serializes the invitation using the same format as Robot Command.
  Uri toUri() {
    final query = <String, String>{
      'endpoint': endpoint.toString().replaceFirst(RegExp(r'/$'), ''),
      'fingerprint': RobotCommandLanClient.normalizeFingerprint(
        certificateFingerprint,
      ),
      'pairing_id': pairingId,
      'code': shortCode,
      'phrase': passphrase,
      'expires': (expiresAt.toUtc().millisecondsSinceEpoch ~/ 1000).toString(),
    };
    return Uri(scheme: scheme, host: host, path: path, queryParameters: query);
  }

  /// Copies this invitation into the generated protobuf access request fields.
  void applyTo(AccessRequest request) {
    request
      ..pairingId = pairingId
      ..pairingCode = shortCode
      ..pairingPhrase = passphrase;
  }

  static bool _isAsciiDigits(String value) =>
      value.runes.every((character) => character >= 0x30 && character <= 0x39);
}
