<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RobotCommand.Observer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/sdk/RobotCommand.Sdk/RobotCommand.Sdk.csproj" />
  </ItemGroup>
</Project>
